version: "2"
services:
  eurekaserver:
#    image: spring-eureka-server:1.0.0
    build: spring-eureka-server/
    restart: always
    network_mode: host
    ports:
      - 8761:8761
    expose:
      - 8761
  zuulgateway:
#    image: zuul-gateway:1.0.0
    build: zuul-gateway/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
    ports:
      - 8090:8090
    expose:
      - 8090
  configserver:
#    image: spring-config-server:1.0.0
    build: spring-config-server/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
    ports:
      - 8888:8888
    expose:
      - 8888
  muzixservice:
#    image: muzix-service:1.0.0
    build: muzix-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - configserver
      - zuulgateway
    ports:
      - 9090:9090
    expose:
      - 9090

  userservice:
#    image: user-service:1.0.0
    build: user-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - configserver
      - zuulgateway
    ports:
      - 8098:8098
    expose:
      - 8098

  mongo:
    image: mongo:3.4-xenial
    restart: always
    network_mode: host
    ports:
      - 27017:27017
    expose:
      - 27017